name: Build Flet APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # سحب الكود
      - name: Checkout repository
        uses: actions/checkout@v4

      # تثبيت بايثون
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # تثبيت Flet + dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flet

      # تثبيت Java & Android SDK (مطلوب عشان apk)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # بناء APK باستخدام Flet
      - name: Build APK
        run: flet build apk

      # حفظ الـ APK كـ Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: build/**/outputs/**/*.apk
